// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/ClearPointNZ/go-crufting/UnitTestingTooling/internal/cruft"
)

type FakeCrufter struct {
	EncruftStub        func(string) (string, error)
	encruftMutex       sync.RWMutex
	encruftArgsForCall []struct {
		arg1 string
	}
	encruftReturns struct {
		result1 string
		result2 error
	}
	encruftReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCrufter) Encruft(arg1 string) (string, error) {
	fake.encruftMutex.Lock()
	ret, specificReturn := fake.encruftReturnsOnCall[len(fake.encruftArgsForCall)]
	fake.encruftArgsForCall = append(fake.encruftArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.EncruftStub
	fakeReturns := fake.encruftReturns
	fake.recordInvocation("Encruft", []interface{}{arg1})
	fake.encruftMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCrufter) EncruftCallCount() int {
	fake.encruftMutex.RLock()
	defer fake.encruftMutex.RUnlock()
	return len(fake.encruftArgsForCall)
}

func (fake *FakeCrufter) EncruftCalls(stub func(string) (string, error)) {
	fake.encruftMutex.Lock()
	defer fake.encruftMutex.Unlock()
	fake.EncruftStub = stub
}

func (fake *FakeCrufter) EncruftArgsForCall(i int) string {
	fake.encruftMutex.RLock()
	defer fake.encruftMutex.RUnlock()
	argsForCall := fake.encruftArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCrufter) EncruftReturns(result1 string, result2 error) {
	fake.encruftMutex.Lock()
	defer fake.encruftMutex.Unlock()
	fake.EncruftStub = nil
	fake.encruftReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeCrufter) EncruftReturnsOnCall(i int, result1 string, result2 error) {
	fake.encruftMutex.Lock()
	defer fake.encruftMutex.Unlock()
	fake.EncruftStub = nil
	if fake.encruftReturnsOnCall == nil {
		fake.encruftReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.encruftReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeCrufter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.encruftMutex.RLock()
	defer fake.encruftMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCrufter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cruft.Crufter = new(FakeCrufter)
